EWPP-914: Ensure drupal 9 compatibility.
openeuropa/oe_corporate_countries pull request #19
Opened 2021-05-26 13:26 UTC by nagyad

2021-05-26 13:34 UTC, yenyasinn commented on README.md
> +- Symlink the theme in  `./build/modules/custom/oe_media` so that it's available for the test site
It won't symlink the theme. Also path is wrong.

2021-05-26 13:37 UTC, nagyad commented on README.md
> +- Symlink the theme in  `./build/modules/custom/oe_media` so that it's available for the test site
Copy-pasta

2021-05-26 14:20 UTC, yenyasinn commented on composer.json
>          "drupal/core-composer-scaffold": "^8.8",
```suggestion
         "drupal/core-composer-scaffold": "^8.9 || ^9",
```

2021-05-26 14:27 UTC, yenyasinn commented on composer.json
>          "drupal/config_devel": "~1.2",
```suggestion
        "drupal/config_devel": "~1.8",
```

2021-05-26 16:13 UTC, yenyasinn commented
Please add name to the testsuite in the phpunit.xml file, otherwise it doesn't pass validation. Please check https://drone.fpfis.eu/openeuropa/oe_corporate_countries/105/21. 
Also add `cacheResult="false"` there also as in another components https://github.com/openeuropa/oe_media/pull/163/files#diff-e35810879ec42bdd81797b3ccb72f6de28a8b4a0e3bfdba43183e133e866b892R2

2021-05-27 08:25 UTC, yenyasinn approved these changes, later dismissed

2021-05-27 14:31 UTC, yenyasinn submitted a review, later dismissed

2021-05-31 10:33 UTC, upchuk requested changes
Install hook takes a parameter `$is_syncing` so we need to use that to check if the install happens in config sync.

Otherwise, looks ok.

2021-05-31 10:33 UTC, upchuk commented on phpunit.xml.dist
> +    <testsuite name="OpenEuropa Corporate Countries">
OpenEuropa Corporate Countries test suite

2021-07-01 08:34 UTC, upchuk approved these changes

2021-07-01 08:35 UTC, brummbar approved these changes

2021-07-01 08:36 UTC, merged