EWPP-1895: Update to PHP8.
openeuropa/oe_corporate_countries pull request #22
Opened 2022-01-19 15:44 UTC by yenyasinn

2022-01-20 16:58 UTC, hernani commented on .drone.yml
>        - composer install --ansi --no-suggest --no-progress
Remove no-suggest

2022-01-20 16:59 UTC, hernani commented on .drone.yml
>        - composer update --prefer-lowest --prefer-stable --ansi --no-suggest --no-progress
Remove no-suggest

2022-01-21 08:30 UTC, yenyasinn commented on .drone.yml
>        - composer install --ansi --no-suggest --no-progress
done

2022-01-24 09:15 UTC, hernani approved these changes

2022-01-24 09:27 UTC, 22Alexandra commented on composer.json
> -            "Drupal\\Tests\\rdf_skos\\": "./build/modules/contrib/rdf_skos/tests/src/"
Why was this removed?

2022-01-24 09:29 UTC, 22Alexandra requested changes

2022-01-24 09:29 UTC, 22Alexandra commented on composer.json
> -            "Drupal\\Tests\\rdf_skos\\": "./build/modules/contrib/rdf_skos/tests/src/"
Why was this removed?

2022-01-24 09:36 UTC, 22Alexandra approved these changes

2022-01-24 09:37 UTC, merged